services:
  frontend:
    image: ollama-mistral_frontend_img
    container_name: ollama-mistral_frontend_ctn
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - 9000:9000
    volumes:
      - ./frontend:/app
    command: /bin/sh -c "yarn && yarn dev"
    depends_on:
      - ollama
  
  ollama:
    container_name: ollama_ctn
    build:
      context: .
      dockerfile: Dockerfile.ollama
      no_cache: true
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama
      - ./secrets/id_ed25519:/root/.ollama/id_ed25519:ro
      - ./secrets/id_ed25519.pub:/root/.ollama/id_ed25519.pub:ro
    restart: unless-stopped

volumes:
  ollama-data: